# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    commit-message:
      prefix: "deps"
    schedule:
      interval: "weekly"
  # Enable version updates for frontend (pnpm)
  - package-ecosystem: "npm"
    # Look for `package.json` and `pnpm-lock.yaml` in the `frontend` directory
    directory: "frontend"
    # Check for updates weekly
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
