version: 2
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
gomod:
  proxy: false
builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -w'
      - '-X github.com/openmanet/openvlm/cmd.Version={{.Version}}'
      - '-X github.com/openmanet/openvlm/cmd.Commit={{.Commit}}'
      - '-X github.com/openmanet/openvlm/cmd.Date={{.Date}}'
    flags:
      - "-trimpath"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: darwin
    env:
      - CGO_ENABLED=1
    overrides:
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
          - CXX=o64-clang++
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CXX=oa64-clang++
    ldflags:
      - '-s -w'
      - '-X github.com/openmanet/openvlm/cmd.Version={{.Version}}'
      - '-X github.com/openmanet/openvlm/cmd.Commit={{.Commit}}'
      - '-X github.com/openmanet/openvlm/cmd.Date={{.Date}}'
    flags:
      - "-trimpath"
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: windows
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -w'
      - '-X github.com/openmanet/openvlm/cmd.Version={{.Version}}'
      - '-X github.com/openmanet/openvlm/cmd.Commit={{.Commit}}'
      - '-X github.com/openmanet/openvlm/cmd.Date={{.Date}}'
    flags:
      - "-trimpath"
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
universal_binaries:
  - name_template: "{{ .ProjectName }}_{{.Version}}"
    # IDs to use to filter the built binaries.
    #
    # Default: the value of the id field
    ids:
      - darwin

    # Whether to remove the previous single-arch binaries from the artifact list.
    # If left as false, your end release might have both several macOS archives:
    # amd64, arm64 and all.
    #
    # Defaults to false.
    replace: false
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
archives:
  - name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
    - goos: windows
      formats: [zip]
    files:
      - README.md
changelog:
  use: github-native
