name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: goreleaser/goreleaser-cross:v1.26.2-3-v2.15.4
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Mark workspace as safe for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
